#!/usr/bin/env bash
# Generated by brain-kit. Starts each persona once; checks only the process list.
set -u
ids=() names=() labels=() dirs=() scripts=()
# @personas@

usage() {
  echo 'Usage: start-all [--tmux|--tabs|--print] [--status] [--wait SECONDS] [--help]'
}
error() { printf '%s\n' "$*" >&2; exit 2; }
backend="${BRAIN_KIT_START_WITH:-auto}"
reason='set by environment variable'
status=0
seconds=20
while [ "$#" -gt 0 ]; do
  case "$1" in
    --tmux|--tabs|--print) backend="${1#--}"; reason='set by argument' ;;
    --status) status=1 ;;
    --wait)
      [ "$#" -ge 2 ] || error '--wait needs a number of seconds'
      shift
      case "$1" in ''|*[!0-9]*) error '--wait must be an integer of 0 or more' ;; esac
      # Avoid arithmetic overflow and octal parsing.
      [ "${#1}" -le 6 ] || error '--wait is limited to 999999 seconds'
      seconds=$((10#$1)) ;;
    --help) usage; exit 0 ;;
    *) usage >&2; error "Unknown argument: $1" ;;
  esac
  shift
done
case "$backend" in auto|tmux|tabs|print) ;; *) error 'BRAIN_KIT_START_WITH must be tmux / tabs / print' ;; esac

refresh() { procs="$(ps -Ao pid=,args=)" || error 'Cannot read the process list'; }
running() {
  printf '%s\n' "$procs" | awk -v wanted="/$1" '
    { $1=""; if (index($0, "claude") && $NF == wanted) found=1 }
    END { exit !found }'
}
prior=()
for ((i=0; i<${#ids[@]}; i++)); do prior[i]=0; done
table() {
  local i state missing=0
  printf '\nName\t/id\tState\n'
  for ((i=0; i<${#ids[@]}; i++)); do
    state='not visible yet'
    if running "${ids[i]}"; then
      if [ "${prior[i]}" = 1 ] || [ "$status" = 1 ]; then state='already running'; else state='started'; fi
    else missing=1
    fi
    printf '%s（%s）\t/%s\t%s\n' "${names[i]}" "${labels[i]}" "${ids[i]}" "$state"
  done
  if [ "$missing" = 1 ]; then
    echo 'Do not run start-all again for personas that are not visible yet.'
    echo 'Look at that tab/window and check with start-all --status.'
  fi
  return "$missing"
}
if [ "$status" = 1 ]; then
  echo 'Check: process list only (starts nothing)'
  refresh
  table
  exit $?
fi

terminal=''
detect_tabs() {
  local candidate
  if [ "$(uname -s)" = Darwin ] && command -v osascript >/dev/null 2>&1; then
    terminal=Terminal
    [ "${TERM_PROGRAM:-}" != iTerm.app ] || terminal=iTerm2
  elif [ "$(uname -s)" = Linux ]; then
    if [ -n "${WSL_DISTRO_NAME:-}" ] && command -v wt.exe >/dev/null 2>&1; then terminal=wt.exe
    elif [ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ]; then
      for candidate in gnome-terminal konsole xfce4-terminal; do
        if command -v "$candidate" >/dev/null 2>&1; then terminal="$candidate"; break; fi
      done
    fi
  fi
  [ -n "$terminal" ]
}
if [ "$backend" = auto ]; then
  if [ -n "${TMUX:-}" ]; then backend=tmux; reason='inside tmux'
  elif command -v tmux >/dev/null 2>&1 && tmux list-sessions >/dev/null 2>&1; then
    backend=tmux; reason='a tmux session exists'
  elif detect_tabs; then backend='tabs'; reason="terminal available: $terminal"
  elif command -v tmux >/dev/null 2>&1; then backend=tmux; reason='create a new tmux session'
  else backend=print; reason='no usable terminal found'
  fi
fi
if [ "$backend" = tmux ]; then
  command -v tmux >/dev/null 2>&1 || error 'tmux is missing. Use --tabs or --print'
elif [ "$backend" = tabs ]; then
  detect_tabs || error 'No usable terminal. Use --tmux or --print'
fi
printf 'Start method: %s (%s)\n' "$backend" "$reason"
[ "$terminal" != Terminal ] || echo 'Terminal.app opens a new window for each persona.'
session="${BRAIN_KIT_TMUX_SESSION:-brain-kit}"
# Quote for the shell and for AppleScript separately.
# Keep the replacement in a variable (bash 3.2 mishandles quotes written in the replacement).
quote() { local q="'\\''"; printf "'%s'" "${1//\'/$q}"; }
apple_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}
launch() {
  local id="$1" dir="$2" script="$3" cmd escaped
  cmd="cd $(quote "$dir") && exec $(quote "$script")"
  case "$backend" in
    tmux)
      if tmux has-session -t "$session" >/dev/null 2>&1; then
        tmux new-window -d -t "$session:" -n "$id" -c "$dir" "$cmd"
      else tmux new-session -d -s "$session" -n "$id" -c "$dir" "$cmd"
      fi ;;
    tabs)
      case "$terminal" in
        Terminal)
          escaped="$(apple_quote "$cmd")"
          osascript -e "tell application \"Terminal\" to do script \"$escaped\"" ;;
        iTerm2)
          escaped="$(apple_quote "$cmd")"
          osascript -e "tell application \"iTerm2\"
if (count of windows) = 0 then
  create window with default profile
else
  tell current window to create tab with default profile
end if
tell current session of current window to write text \"$escaped\"
end tell" ;;
        wt.exe) wt.exe -w 0 new-tab wsl.exe -d "$WSL_DISTRO_NAME" -- bash -lc "$cmd" ;;
        gnome-terminal) gnome-terminal --tab -- bash -lc "$cmd" ;;
        konsole) konsole --new-tab -e bash -lc "$cmd" ;;
        xfce4-terminal) xfce4-terminal --tab -x bash -lc "$cmd" ;;
      esac ;;
  esac
}
trusted() {
  python3 - "$1" <<'PY'
import json, os, sys
try:
    path = os.path.join(os.environ.get("CLAUDE_CONFIG_DIR") or os.environ["HOME"], ".claude.json")
    with open(path, encoding="utf-8") as f:
        accepted = json.load(f)["projects"][sys.argv[1]]["hasTrustDialogAccepted"] is True
except (OSError, ValueError, KeyError, TypeError):
    accepted = False
sys.exit(0 if accepted else 1)
PY
}
noted=()
trust_note() {
  local dir="$1" id="$2" seen place
  for seen in ${noted[@]+"${noted[@]}"}; do [ "$seen" != "$dir" ] || return 0; done
  noted+=("$dir")
  trusted "$dir" && return 0
  place="the start-$id tab/window"
  [ "$backend" != tmux ] || place="tmux window $id"
  printf '%s: first-time folder trust prompt (%s).\n' "$place" "$dir"
  echo '"Do you trust the files in this folder?"'
  echo 'Press Enter on the first option, "Yes, proceed / Yes, I trust this folder".'
  echo 'Only once per folder.'
}
refresh
for ((i=0; i<${#ids[@]}; i++)); do
  if running "${ids[i]}"; then
    prior[i]=1
    printf '%s: already running. Not starting it again.\n' "${names[i]}"
  elif [ "$backend" = print ]; then
    printf 'Open a new terminal tab and run: %s\n' "$(quote "${scripts[i]}")"
  else
    trust_note "${dirs[i]}" "${ids[i]}"
    launch "${ids[i]}" "${dirs[i]}" "${scripts[i]}" || printf '%s: could not request the start. Not retrying; check the list.\n' "${names[i]}" >&2
  fi
done
if [ "$backend" = print ]; then echo 'Then check: start-all --status'; exit 0; fi
if [ "$backend" = tmux ]; then
  if [ -n "${TMUX:-}" ]; then printf 'View: tmux switch-client -t %q\n' "$session"
  else printf 'View: tmux attach -t %q\n' "$session"
  fi
  echo 'Move: Ctrl-b then the window number, or Ctrl-b w.'
fi
for ((elapsed=0; ; elapsed++)); do
  refresh
  missing=0
  for ((i=0; i<${#ids[@]}; i++)); do
    running "${ids[i]}" || missing=1
  done
  if [ "$missing" = 0 ] || [ "$elapsed" -ge "$seconds" ]; then break; fi
  sleep 1
done
if [ "$backend" = tmux ]; then
  for ((i=0; i<${#ids[@]}; i++)); do
    [ "${prior[i]}" = 0 ] || continue
    if tmux capture-pane -p -t "$session:${ids[i]}" 2>/dev/null | grep -qi trust; then
      printf 'Window %s is waiting at the folder trust prompt.\n' "${ids[i]}"
      printf 'Attach, go to window %s, and press Enter on Yes.\n' "${ids[i]}"
    fi
  done
fi
table
